### ISSUE TITLE
Crowdstrike isn't showing up in Munki reports properly

### ISSUE THREAD

**Issue by SujeevPachala** [dcoobs/crowdstrike#2]
For some reasons the CS isn't showing up in my Munki Reports
Is there a way I can remove and fix it?

<img width="1553" alt="Screen Shot 2022-11-18 at 4 50 01 PM" src="https://user-images.githubusercontent.com/113067854/202694378-d3c12ef7-fe43-4c9b-a3c7-e62a7a7b3374.png">

I am using Crowdstrike 6:45 and we support macOS 10.x till 13.x

**Comment by dcoobs** [comment]
Have you checked your .env file to ensure that the module is enabled? This can be done by adding `crowdstrike` to the _`MODULES=`_ setting. Once that's completed, your endpoints will need a new client package installed that includes the CS module scripts. If you want to remove the module, you should be able to uninstall it via Composer or by removing the module's files manually. The wiki has some information on installing and removing modules: [https://github.com/munkireport/munkireport-php/wiki/Module-Overview](https://github.com/munkireport/munkireport-php/wiki/Module-Overview)
